import { NextRequest, NextResponse } from "next/server";
import { db } from "@/db";
import { resumeSessions } from "@/db/schema";
import { eq } from "drizzle-orm";
import JSZip from "jszip";
import { getQuotaStatus, recordAction } from "@/lib/usage";
import { auth } from "@/auth";
import { logger } from "@/lib/logger";

export async function GET(request: NextRequest) {
  try {
    const session = await auth();
    const { searchParams } = new URL(request.url);
    const sessionId = searchParams.get("sessionId");

    if (!sessionId) {
      return NextResponse.json(
        { error: "Session ID is required." },
        { status: 400 }
      );
    }

    const [resumeSession] = await db
      .select()
      .from(resumeSessions)
      .where(eq(resumeSessions.id, sessionId))
      .limit(1);

    if (!resumeSession || !resumeSession.latexSource) {
      return NextResponse.json(
        {
          error:
            "We couldn't find that session — it may have expired. Start a new resume.",
        },
        { status: 404 }
      );
    }

    // Check quota
    const userId = session?.user?.id;
    const quota = await getQuotaStatus({
      action: "export_zip",
      userId,
      sessionId,
    });

    if (quota.isAtLimit) {
      return NextResponse.json(
        {
          error:
            "You've reached the abuse limit for ZIP downloads. Please try again next month.",
          code: "QUOTA_EXCEEDED",
          quota,
        },
        { status: 403 }
      );
    }

    // Build ZIP
    const zip = new JSZip();
    const template = resumeSession.selectedTemplate ?? "classic";
    const latex = resumeSession.latexSource;

    zip.file("main.tex", latex);
    zip.file(
      "README.md",
      `# Resume LaTeX Source

Generated by [TeXume](https://texume.app) using the **${template}** template.

## Compiling

\`\`\`bash
# Using Tectonic (recommended)
tectonic main.tex

# Using pdflatex
pdflatex main.tex
\`\`\`

## Requirements

- Tectonic (https://tectonic-typesetting.github.io/) OR
- A full LaTeX distribution (TeX Live, MiKTeX)
`
    );

    const zipBuffer = await zip.generateAsync({ type: "nodebuffer" });

    // Record usage
    await recordAction({ action: "export_zip", userId, sessionId });

    return new Response(zipBuffer.buffer as ArrayBuffer, {
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": 'attachment; filename="resume-source.zip"',
        "Content-Length": String(zipBuffer.byteLength),
      },
    });
  } catch (err) {
    logger.error("ZIP export error", { error: String(err) });
    return NextResponse.json(
      { error: "Something went wrong on our end. We've been notified." },
      { status: 500 }
    );
  }
}
